### ISSUE TITLE
spelling correction `dotnet pyblish`

### ISSUE THREAD

**Issue by ThiagodePaulaSouza** [fl0zone/fl0-docs#25]
https://github.com/fl0zone/fl0-docs/blob/135cf82cdd04eae84fa45e39953ede64142bc5ef/docs/builds/buildpacks/dotnet.md?plain=1#L60

```md
### Configuring the `dotnet publish` Command
```

**Comment by stennie** [comment]
Thanks for the bug report @ThiagodePaulaSouza !

Regards,
Stennie

**Comment by stennie** [comment]
Fixed via #38
